// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzdxbxqxjqaxpiuzbhdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6ZHhieHF4anFheHBpdXpiaGRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NzQwODgsImV4cCI6MjA2MjA1MDA4OH0.ZVMTua9aXjIibJKcgTcTQq1VMzUzdjts5FFEqxHXFJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);